apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml          # frontend
  - service.yaml             # frontend service
  - hpa.yaml
  - backend-deployment.yaml
  - backend-service.yaml

images:
  - name: _placeholder
    newName: <will-be-replaced>
    newTag: latest
  - name: _placeholder-backend
    newName: <will-be-replaced>
    newTag: latest