apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml

# This placeholder will be replaced by the pipeline
images:
  - name: _placeholder
    newName: <will-be-replaced>
    newTag: latest