apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# Track all active resource assets
resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
   
# This block allows our pipeline to inject unique image hashes safely
images:
  - name: ://amazonaws.com
    newTag: latest
    
