apiVersion: v1
kind: Service
metadata:
  name: resume-service
  namespace: resume
  annotations:
    # 🏎️ DEVOPS OPTIMIZATION: Auto provisions an enterprise-grade AWS Network Load Balancer (NLB)
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: resume-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Upgraded from NodePort to expose your app to the public web safely
